# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - models-gateway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_0ddbbff085b944638f4292cc8cde05fe }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4e21058011e94a2e91a35ff05469c0a8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0ddbbff085b944638f4292cc8cde05fe }}/bilalauz/models-gateway:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'models-gateway'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_76a78e8c3fcf408fbcb7c373284167b4 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0ddbbff085b944638f4292cc8cde05fe }}/bilalauz/models-gateway:${{ github.sha }}'